apiVersion: v1
kind: Service
metadata:
  name: leaderboard-app-service
  namespace: leaderboard-app
spec:
  selector:
    app: leaderboard-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
