# Use Node.js image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app files
COPY . .

# Expose the application port
EXPOSE 4000

# Run the leaderboard app
CMD ["node", "leaderboard.js"]
